name: riverpod_calculator_app
description: "A new Flutter project."

publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Application Dependiencies Here
dependencies:
  flutter:
    sdk: flutter


  # Cupertino icons libreary
  cupertino_icons: ^1.0.8
  # Sate management ---> Riverpod
  flutter_riverpod: ^2.6.1
  # App router ---> GoRouter
  go_router: ^15.0.0


# Dev dependencies here
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  # Use material design 
  uses-material-design: true
  
  assets:
  # Asset of font directory
    - assets/fonts/
  # Asset of Icon directory
    - assets/icons/



  fonts:
  # Fancy fonts style 
    - family: Minecraft
      fonts:
        - asset: assets/fonts/MinecraftTen-VGORe.ttf
          weight: 800
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
